(() => {
  'use strict';
  const P=window.PM,$=id=>document.getElementById(id),e=P.esc;
  let mediaScene='',state,route='library',libraryTab='presets',filter='all',query='',editorTab='content',currentId='',device='pc',mobilePreview=false,maker=null,selectedNode=null,findOpen=false,imageSlot='main',saveTimer,saveQueue=Promise.resolve(),saveRevision=0,toastTimer;
  const app=$('app'),dialog=$('dialog');
  const current=()=>state.logs.find(x=>x.id===currentId);
  const mediaData=l=>l.preset.design?.editor&&mediaScene?window.PMEditors.sceneData(l,l.scenes.find(s=>s.id===mediaScene)||l.scenes[0]):l;
  const activeImage=source=>{const l=mediaData(source);if(imageSlot.startsWith('film:'))return window.PMEditors.collection(source,l).find(p=>p.id===imageSlot.slice(5))?.image||l.image;return imageSlot==='main'||!source.preset.design?l.image:((l.designImages||={})[imageSlot]||=({src:'',ratio:source.preset.design.images.find(i=>i.id===imageSlot)?.ratio||'1/1',width:100,x:50,y:50}));};
  const button=(label,action,extra='',cls='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
  const field=(label,bind,value,type='text',attrs='')=>`<label class="field"><span>${e(label)}</span><input type="${type}" data-bind="${bind}" value="${e(value)}" ${attrs}></label>`;
  function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200);}
  function status(message){$('saveStatus').textContent=message;}
  let pendingSave=false;
  function dirty(touchLog=true){state.lastLogId=currentId;state.maker=maker;state.savedAt=Date.now();if(touchLog&&current())current().updatedAt=Date.now();saveRevision++;pendingSave=true;try{localStorage.setItem('preset-maker-recovery',JSON.stringify(state));}catch{}status('저장 중…');clearTimeout(saveTimer);saveTimer=setTimeout(flush,180);}
  function flush(){clearTimeout(saveTimer);const revision=saveRevision,snapshot=P.clone(state);saveQueue=saveQueue.catch(()=>{}).then(()=>P.writeStore(snapshot)).then(()=>{if(revision===saveRevision){pendingSave=false;try{localStorage.removeItem('preset-maker-recovery');}catch{}status('● 자동 저장됨 · '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'}));}return true;}).catch(err=>{status('저장 실패 · 백업을 내려받아 주세요');toast('저장하지 못했어요. 전체 백업으로 작업을 보관해 주세요.');console.error(err);return false;});return saveQueue;}
  function download(name,content,type='application/json'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name.replace(/[<>:"/\\|?*]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const packageOf=(type,data)=>JSON.stringify({format:'log-studio-preset-maker',version:1,type,data},null,2);
  function modal(title,body){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=body;if(!dialog.open)dialog.showModal();}
  function closeModal(){dialog.close();}
  function pickFile(accept,callback){const input=$('fileInput');input.accept=accept;input.value='';input.onchange=async()=>{const file=input.files[0];if(!file)return;try{if(file.size>40*1024*1024)throw new Error('40MB 이하 파일을 선택해 주세요.');await callback(file);}catch(err){toast(err.message);}};input.click();}
  function setRoute(next){route=next;if(next==='editor'&&!current()){currentId=state.lastLogId||state.logs[0]?.id||'';if(!current())newLog(state.presets[0],false);}location.hash=next;render();}
  function newLog(preset,navigate=true){const log=P.createLog(preset);imageSlot='main';mediaScene='';state.logs.unshift(log);currentId=log.id;dirty();if(navigate)setRoute('editor');}
  function render(){if(route==='editor'&&current()?.preset.kind==='custom'&&editorTab==='images'&&!current().preset.fields.some(f=>f.role==='image'))editorTab='content';document.querySelectorAll('.main-nav button').forEach(b=>{b.classList.toggle('active',b.dataset.value===route);b.setAttribute('aria-current',b.dataset.value===route?'page':'false');});app.innerHTML=route==='library'?library():route==='maker'?makerView():editor();if(route==='library')hydrateThumbs();else{adaptCustomUI();updatePreview();}}
  function adaptCustomUI(){const log=current();if(route!=='editor'||log?.preset.kind!=='custom')return;const has=role=>log.preset.fields.some(f=>f.role===role);if(!has('image'))document.querySelector('[data-action="editor-tab"][data-value="images"]')?.remove();if(!has('subtitle'))document.querySelector('[data-bind="subtitle"]')?.closest('.field')?.remove();if(!has('title')){const label=document.querySelector('[data-bind="title"]')?.previousElementSibling;if(label)label.textContent='작업 이름';}document.querySelector('[data-bind="note"]')?.closest('details')?.remove();if(!has('body')&&$('bodyInput')){const notice=document.createElement('div');notice.className='note sand';notice.textContent='이 틀에는 전체 본문 입력칸이 없어요. 아래 원고는 보관되며, 별도 입력칸으로 내용을 작성할 수 있어요.';$('bodyInput').before(notice);}}
  function library(){const presets=state.presets.filter(p=>(filter!=='favorite'||p.favorite)&&(filter==='all'||filter==='favorite'||p.category===filter)&&(!query||(p.name+' '+p.description).toLowerCase().includes(query.toLowerCase())));const logs=state.logs.filter(x=>!query||x.title.toLowerCase().includes(query.toLowerCase()));
    return `<div class="library-shell"><aside class="library-nav" aria-label="프리셋 분류"><div class="eyebrow">PRESETS</div>${[['all','전체'],['favorite','즐겨찾기'],['문서','# 문서'],['대화','# 대화'],['기록','# 기록'],['장르','# 장르'],['내 프리셋','# 내 프리셋']].map(([value,label])=>button(label+'<small>'+state.presets.filter(p=>value==='all'||(value==='favorite'?p.favorite:p.category===value)).length+'</small>','filter',`data-value="${value}"`,filter===value?'active':'')).join('')}<div class="nav-backup">${button('전체 백업 내려받기','backup')}${button('백업에서 복원','import')}</div></aside><div class="library"><div class="library-tabs">${button(`프리셋 <span class="badge">${state.presets.length}</span>`,'library-tab','data-value="presets"',libraryTab==='presets'?'active':'')}${button(`작성한 로그 <span class="badge pink">${state.logs.length}</span>`,'library-tab','data-value="logs"',libraryTab==='logs'?'active':'')}</div><div class="library-toolbar"><input id="librarySearch" class="search" placeholder="이름·태그로 찾기" aria-label="보관함 검색" value="${e(query)}"><span class="spacer"></span>${libraryTab==='presets'?button('순서 변경','preset-order'):''}${button('파일 가져오기','import')}${button(libraryTab==='presets'?'프리셋 내보내기':'전체 백업','export-library')}${button('+ HTML로 새 프리셋','route','data-value="maker"','primary')}</div>${libraryTab==='presets'?`<div class="preset-grid">${presets.map(p=>presetCard(p)).join('')}</div>${!presets.length?'<div class="empty"><h3>조건에 맞는 프리셋이 없어요</h3><p>다른 이름이나 태그로 찾아보세요.</p></div>':''}<div class="row recent-heading"><h2>최근 작성한 로그</h2><span class="badge pink">${state.logs.length}</span>${button('모두 보기 →','library-tab','data-value="logs"','text-button spacer')}</div>${logsView(state.logs.slice(0,3))}`:logsView(logs)}<div class="library-foot"><span><i class="dot"></i>이 브라우저에 자동 저장됩니다.</span><span>작업을 옮기거나 보관하려면 전체 백업을 내려받으세요.</span>${button('전체 백업','backup','','text-button')}${button('복원','import','','text-button')}</div></div></div>`;
  }
  function presetCard(p){return `<article class="preset-card"><button class="thumbnail" data-action="new-log" data-id="${e(p.id)}" aria-label="${e(p.name)} 프리셋으로 로그 쓰기"><iframe tabindex="-1" title="${e(p.name)} 디자인 썸네일" data-thumb="${e(p.id)}" sandbox=""></iframe></button><div class="card-name"><h3>${e(p.name)}</h3>${button(p.favorite?'★':'☆','favorite',`data-id="${e(p.id)}" aria-label="${e(p.name)} 즐겨찾기" aria-pressed="${!!p.favorite}"`,'star '+(p.favorite?'on':''))}</div><div class="card-meta">${e(p.description||'내 HTML 프리셋')}</div><div class="card-footer">${button('로그 쓰기 ↗','new-log',`data-id="${e(p.id)}"`,'text-button small')}${button('복제','duplicate-preset',`data-id="${e(p.id)}"`,'text-button small')}${button('⋯','preset-menu',`data-id="${e(p.id)}" aria-label="${e(p.name)} 관리"`,'text-button small')}</div></article>`;}
  function logsView(logs){if(!logs.length)return `<div class="empty"><div class="empty-symbol">✧</div><h3>첫 번째 이야기를 기다리고 있어요</h3><p>프리셋에서 ‘로그 쓰기’를 누르면 새 작업이 시작돼요.</p>${button('기본 프리셋으로 시작','new-log',`data-id="${e(state.presets[0]?.id||'')}"`,'soft')}</div>`;return `<div class="log-grid">${logs.map(l=>`<article class="log-card"><div class="row between"><h3>${e(l.title||'제목 없는 로그')}</h3>${button('⋯','log-menu',`data-id="${e(l.id)}" aria-label="로그 관리"`,'icon-button')}</div><p>${e(l.preset.name)} · ${new Date(l.updatedAt).toLocaleDateString('ko-KR')}</p><div class="row between"><span class="badge"><i class="dot"></i>저장한 작업</span>${button('이어서 쓰기 →','open-log',`data-id="${e(l.id)}"`,'text-button small')}</div></article>`).join('')}</div>`;}
  function hydrateThumbs(){document.querySelectorAll('[data-thumb]').forEach(frame=>{const p=state.presets.find(x=>x.id===frame.dataset.thumb);const sample=P.createLog(p);const html=p.design?window.PMDesign.render(sample,{placeholders:true}):P.render(sample);frame.srcdoc=P.documentHTML('<style>html,body{overflow:hidden}</style>'+html);const scale=frame.parentElement.clientWidth/640;frame.style.transform=`scale(${scale})`;});}
  function editor(){const l=current();if(!l)return '';return `<div class="work-titlebar"><div><h1 id="editorHeading">${e(l.title||'제목 없는 로그')}</h1><div class="meta"><span id="presetLabel">${e(l.preset.name)}</span> ${button('교체','switch-preset','','text-button small')}<span class="badge">이 로그에만 적용</span></div></div><div class="work-actions">${button('새 로그','new-log',`data-id="${e(l.preset.id)}"`)}${button('프로젝트 저장 ↓','export-project')}${button('게시용 HTML','export-html','','primary')}</div></div><div class="mobile-switch">${button('입력','mobile-view','data-value="input"',mobilePreview?'':'soft')}${button('미리보기','mobile-view','data-value="preview"',mobilePreview?'soft':'')}</div><div class="workspace ${mobilePreview?'show-preview':''}"><section class="editor-panel"><div class="panel-tabs">${[['content','내용'],['images','이미지'],['style','모양']].map(([value,label])=>button(label,'editor-tab',`data-value="${value}"`,editorTab===value?'active':'')).join('')}</div><div class="panel-content">${editorTab==='content'?contentPanel(l):editorTab==='images'?imagesPanel(l):stylePanel(l)}</div></section>${previewPanel('editor-preview')}</div>`;}
  function contentPanel(l){return `<div class="field-grid">${field(l.preset.design?.editor?.titleLabel||'로그 제목','title',l.title)}${!l.preset.design||l.preset.design.config.subtitle?field(l.preset.design?.editor?.subtitleLabel||'부제','subtitle',l.subtitle):''}</div><div class="row between section-heading"><h3>로그 원고</h3><span class="badge">통째로 붙여넣기</span></div><p class="field-hint" style="margin-bottom:12px">서술과 대사를 한 번에 넣으세요. 화자가 있는 대사도 함께 읽어드려요.</p>${findOpen?findPanel():''}<div class="format-toolbar">${button('<b>B</b>','format','data-format="bold" title="굵게"')}${button('<i>강조</i>','format','data-format="em"')}${button('구분선','format','data-format="hr"')}${button('접기','format','data-format="fold"')}${button('화자','format','data-format="speaker"')}${button('찾기·바꾸기','find','','spacer')}</div><textarea id="bodyInput" class="body-input" data-scene-body="${e(l.scenes[0].id)}" aria-label="전체 로그 원고" spellcheck="false">${e(l.scenes[0].body)}</textarea><div class="source-summary"><span id="charCount">${l.scenes.reduce((n,s)=>n+s.body.length,0).toLocaleString()}자 · ${l.scenes.length}개 장면</span>${button('문법 안내','syntax','','text-button small')}</div><div class="row between"><h3>${e(l.preset.design?.editor?.unit||'장면')}</h3>${button('+ '+(l.preset.design?.editor?.unit||'장면')+' 추가','add-scene','','text-button small')}</div><div class="scene"><div class="scene-bar"><span class="badge">01</span><input aria-label="첫 장면 이름" data-scene-title="${e(l.scenes[0].id)}" value="${e(l.scenes[0].title)}">${sceneButtons(l.scenes[0],0)}</div>${l.scenes[0].hidden?'<div class="note">이 장면은 출력에서 숨겨져 있어요.</div>':''}</div>${l.scenes.slice(1).map((s,i)=>`<details class="scene ${s.hidden?'hidden-scene':''}"><summary class="scene-bar"><span class="badge">${String(i+2).padStart(2,'0')}</span><span>${e(s.title)}</span><span class="spacer muted">${s.body.length}자 ${s.hidden?'· 숨김':''}</span></summary><div class="scene-body"><div class="row">${field('장면 이름','',s.title,'text',`data-scene-title="${e(s.id)}"`)}${sceneButtons(s,i+1)}</div><textarea data-scene-body="${e(s.id)}" aria-label="${e(s.title)} 원고">${e(s.body)}</textarea></div></details>`).join('')}${(l.preset.design?.editor&&l.preset.design.config.subtitle||l.preset.fields?.some(f=>f.role==='scene-subtitle'))?l.scenes.map((s,i)=>field((i+1)+'번 장면 부제','scenes.'+i+'.subtitle',s.subtitle||'')).join(''):''}${specialPanel(l)}${customPanel(l)}<details class="special"><summary>추가 링크 · 메모</summary>${field('추가 참고 링크','link',l.link,'url')}<label class="field"><span>추가 메모</span><textarea data-bind="note" rows="3">${e(l.note)}</textarea></label></details>${l.orphaned?.length?`<details class="special"><summary>보관 항목 <span class="badge pink">${l.orphaned.length}</span></summary><p class="field-hint">이전 프리셋의 전용 설정을 보존했어요. 같은 틀로 돌아가면 다시 연결돼요.</p>${l.orphaned.map(x=>`<div class="note" style="margin-top:8px">${e(x.name)} · 전용 설정 ${Object.keys(x.values||{}).length}개</div>`).join('')}</details>`:''}`;}
  function sceneButtons(s,i){return `<span class="row spacer">${button('↑','move-scene',`data-id="${e(s.id)}" data-value="-1" aria-label="장면 위로" ${i===0?'disabled':''}`,'text-button small')}${button('↓','move-scene',`data-id="${e(s.id)}" data-value="1" aria-label="장면 아래로" ${i===current().scenes.length-1?'disabled':''}`,'text-button small')}${button('복제','duplicate-scene',`data-id="${e(s.id)}"`,'text-button small')}${button(s.hidden?'보이기':'숨기기','hide-scene',`data-id="${e(s.id)}"`,'text-button small')}</span>`;}
  function specialPanel(l){const fields=l.preset.special||[];if(!fields.length)return '';if(l.preset.design?.editor)return `<label class="field"><span>설정을 바꿀 ${e(l.preset.design.editor.unit)}</span><select id="mediaScene">${l.scenes.map(s=>`<option value="${e(s.id)}" ${(mediaScene||l.primarySceneId||l.scenes[0].id)===s.id?'selected':''}>${e(s.title)}${s.hidden?' (숨김)':''}</option>`).join('')}</select></label>`+[...new Set(fields.map(f=>f.group||'설정'))].map(group=>`<details class="special" open><summary>${e(group)}</summary>${fields.filter(f=>(f.group||'설정')===group).map(f=>specialField(f,mediaData(l).values[f.key])).join('')}</details>`).join('');return `<details class="special" ${l.preset.design?'':'open'}><summary>${e(l.preset.name)} ${l.preset.design?'디자인 문구':'설정'} <span class="badge pink">프리셋 전용</span></summary>${fields.map(f=>specialField(f,l.values[f.key])).join('')}</details>`;}
  function specialField(f,value){const bind='values.'+f.key;if(f.type==='textarea')return `<label class="field"><span>${e(f.label)}</span><textarea data-bind="${bind}" rows="3">${e(value)}</textarea></label>`;if(f.type==='list'||f.type==='checklist'){return `<div class="field"><span>${e(f.label)}</span>${(value||[]).map((item,i)=>`<div class="row-list-item">${f.type==='checklist'?`<input type="checkbox" aria-label="목표 완료" data-list-check="${e(f.key)}" data-index="${i}" ${item.done?'checked':''}>`:''}<input type="text" aria-label="${e(f.label)} ${i+1}" data-list-text="${e(f.key)}" data-index="${i}" value="${e(f.type==='list'?item:item.text)}">${button('↑','list-move',`data-key="${e(f.key)}" data-index="${i}" ${i===0?'disabled':''} aria-label="항목 위로"`,'text-button')}${button('×','list-remove',`data-key="${e(f.key)}" data-index="${i}" aria-label="항목 삭제"`,'text-button')}</div>`).join('')}${button('+ 항목 추가','list-add',`data-key="${e(f.key)}"`,'text-button small')}</div>`;}
    if(f.type==='checkbox')return `<label class="field row"><input type="checkbox" data-bind="${bind}" ${value?'checked':''}> ${e(f.label)}</label>`;
    if(f.type==='select')return `<label class="field"><span>${e(f.label)}</span><select data-bind="${bind}">${f.options.map(o=>`<option ${o===value?'selected':''}>${e(o)}</option>`).join('')}</select></label>`;
    if(f.type==='range')return `<label class="field"><span>${e(f.label)} <output data-range-value="${bind}">${e(value)}%</output></span><input type="range" min="0" max="100" data-bind="${bind}" value="${e(value)}"></label>`;
    return field(f.label,bind,value,f.type, f.type==='number'?`min="${f.min??0}" max="${f.max??999999}"`:'');
  }
  function customPanel(l){if(l.preset.kind!=='custom')return '';const fields=l.preset.fields.filter(f=>['text','link','image'].includes(f.role)&&!(f.role==='image'&&l.preset.fields.filter(x=>x.role==='image').length===1));return fields.length?`<details class="special" open><summary>이 HTML의 입력칸</summary>${fields.map(f=>field(f.name,'custom.'+f.id,l.custom[f.id]||'',f.role==='link'?'url':'text')).join('')}</details>`:'';}
  function collectionPanel(l){
    if(!l.preset.design?.editor?.collection)return '';
    const photos=window.PMEditors.collection(l,mediaData(l));
    return `<details class="special" open><summary>필름 사진 ${photos.filter(p=>!p.hidden).length}장</summary>${photos.map((p,i)=>`<div class="film-row"><span>${i+1}</span><input aria-label="사진 ${i+1} 설명" data-film-caption="${e(p.id)}" value="${e(p.caption)}">${button('편집','film-select',`data-id="${e(p.id)}"`)}${button('복제','film-copy',`data-id="${e(p.id)}"`)}${button('↑','film-up',`data-id="${e(p.id)}" ${i===0?'disabled':''} aria-label="사진 ${i+1} 위로"`)}${button('↓','film-down',`data-id="${e(p.id)}" ${i===photos.length-1?'disabled':''} aria-label="사진 ${i+1} 아래로"`)}${button(p.hidden?'보이기':'숨기기','film-hide',`data-id="${e(p.id)}"`)}</div>`).join('')}${button('+ 사진 추가','film-add','','soft')}</details>`;
  }
  function imageChoices(l){return [...(l.preset.design?.images||[]),...window.PMEditors.collection(l,mediaData(l)).map((p,i)=>({id:'film:'+p.id,label:'필름 '+(i+1)+' · '+p.caption+(p.hidden?' (숨김)':'')}))];}
  function imagesPanel(l){const framed=['cheki','polaroid','photocard'].includes(l.preset.kind),img=activeImage(l),imageBind='activePhoto';return `<h3 style="margin-bottom:14px">이미지</h3>${l.preset.design?.editor?`<label class="field"><span>이미지를 넣을 ${e(l.preset.design.editor.unit)}</span><select id="mediaScene">${l.scenes.map(s=>`<option value="${e(s.id)}" ${(mediaScene||l.primarySceneId||l.scenes[0].id)===s.id?'selected':''}>${e(s.title)}${s.hidden?' (숨김)':''}</option>`).join('')}</select></label>`:''}${l.preset.design?`<label class="field"><span>바꿀 이미지</span><select id="imageSlot">${imageChoices(l).map(i=>`<option value="${i.id}" ${i.id===imageSlot?'selected':''}>${e(i.label)}</option>`).join('')}</select></label>`:''}${collectionPanel(l)}<div class="note" style="margin-bottom:18px">이미지가 없으면 해당 공간도 함께 숨겨져요.</div>${img.src?`<img class="image-preview" src="${e(P.url(img.src,true))}" alt="현재 대표 이미지"><div class="row" style="margin-bottom:15px">${button('이미지 교체','image-file','','soft')}${button('이미지 삭제','image-clear','','text-button')}</div>`:`<div class="image-drop" id="imageDrop" role="button" tabindex="0" data-action="image-file"><strong>이미지를 여기에 놓으세요</strong><small>파일 선택 · 끌어놓기 · Ctrl+V 붙여넣기</small></div>`}<div style="margin-top:20px">${field('이미지 주소',imageBind+'.src',img.src.startsWith('data:')?'':img.src,'url','placeholder="https://…"')}</div><label class="field"><span>비율</span><select data-bind="${imageBind}.ratio">${[['auto','원본'],[img.ratio,img.ratio==='auto'?'원본':img.ratio.replace(/\s*\/\s*/g,':')],['16/9','16:9'],['4/3','4:3'],['1/1','1:1'],['3/4','3:4'],['46/62','체키 사진 46:62']].map(([v,t])=>`<option value="${v}" ${v===img.ratio?'selected':''}>${t}</option>`).join('')}</select></label>${[['width','크기',10,100],['x','가로 위치',0,100],['y','세로 위치',0,100]].map(([k,t,min,max])=>`<label class="range-row"><span>${t}</span><input type="range" min="${min}" max="${max}" value="${img[k]}" data-bind="${imageBind}.${k}"><output data-range-value="${imageBind}.${k}">${img[k]}%</output></label>`).join('')}<p class="field-hint">위치는 비율에 맞춰 잘린 사진에서 보이는 부분을 조절해요.</p>${button(framed?'프레임 포함 한 장 PNG 저장':'사진 영역만 PNG 저장',framed?'card-png':'photo-only','','soft')}${l.preset.kind==='photocard'?button('뒷면 PNG 저장','card-back-png','','soft'):''}<p class="field-hint">${framed?'사진·프레임·안의 글씨·스티커를 함께 저장해요. 체키는 테이프와 기울기 없이 반듯하게 저장돼요. 바깥 제목·본문은 제외해요.':'현재 비율과 위치로 사진 영역만 저장해요.'}</p>`;}
  function stylePanel(l){return `<h3 style="margin-bottom:15px">글과 여백</h3><div class="note" style="margin-bottom:20px">변경한 모양은 현재 로그에만 저장돼요.</div>${field('폰트 이름 직접 입력','style.font',l.style.font)}<p class="field-hint" style="margin-top:-10px;margin-bottom:18px">설치된 폰트 이름을 쓸 수 있어요. 다른 기기에는 대체 글꼴이 표시될 수 있어요.</p><div class="field-grid">${field('글자 크기 (px)','style.size',l.style.size,'number','min="9" max="64" step="1"')}${field('줄 간격','style.line',l.style.line,'number','min="1" max="3" step="0.1"')}${field('안쪽 여백 (px)','style.padding',l.style.padding,'number','min="0" max="100" step="2"')}</div><div class="section-heading"><h3>색상</h3></div><div class="field-grid">${field('본문','style.ink',l.style.ink,'color')}${field('배경','style.paper',l.style.paper,'color')}${field('강조','style.accent',l.style.accent,'color')}</div><div class="row" style="margin:10px 0 22px">${P.palette.map(c=>button('', 'accent',`data-value="${c}" style="background:${c};width:33px;height:33px;padding:0" aria-label="강조색 ${c}"`)).join('')}</div><details class="special"><summary>특정 장면만 조절</summary><label class="field"><span>장면</span><select id="styleScene">${l.scenes.map(s=>`<option value="${e(s.id)}">${e(s.title)}</option>`).join('')}</select></label><div class="field-grid"><label class="field"><span>글자 크기</span><input id="sceneSize" type="number" min="9" max="64" value="${l.style.size}"></label><label class="field"><span>본문 색</span><input id="sceneInk" type="color" value="${l.style.ink}"></label></div>${button('선택 장면에 적용','scene-style','','soft')}</details>${button('현재 모양을 새 프리셋으로 저장','save-styled-preset','','soft')}`;}
  function previewPanel(cls=''){return `<section class="preview-panel ${cls}"><div class="preview-toolbar"><span>미리보기 <span style="opacity:.6">· 누르면 입력칸으로 이동</span></span><div class="segmented">${button('PC','device','data-value="pc"',device==='pc'?'active':'')}${button('모바일','device','data-value="mobile"',device==='mobile'?'active':'')}</div></div><div class="preview-scroll"><iframe id="previewFrame" title="로그 실시간 미리보기" class="preview-frame ${device==='mobile'?'mobile':''}" sandbox="allow-scripts"></iframe></div><div class="preview-note">디자인의 색을 그대로 볼 수 있도록 중립 배경을 사용해요.</div></section>`;}
  function findPanel(){return `<div class="find-box"><div class="row"><input id="findText" aria-label="찾을 내용" placeholder="찾을 내용"><input id="replaceText" aria-label="바꿀 내용" placeholder="바꿀 내용"></div><div class="row"><label style="font-size:11px"><input id="includeHidden" type="checkbox"> 숨긴 장면 포함</label>${button('모두 바꾸기','replace-all','','small spacer')}${button('닫기','find','','text-button small')}</div></div>`;}
  function makerView(){if(!maker?.html)return `<div class="import-start"><div class="import-hero"><div class="eyebrow">MAKE YOUR OWN PRESET</div><h1>좋아하는 디자인을, 나만의 틀로.</h1><p>HTML을 가져와 바꿔 쓸 부분을 골라 주세요.</p></div><div class="panel-card"><div class="row between" style="margin-bottom:14px"><h3>원본 HTML</h3>${button('HTML 파일 열기','html-file','','small')}</div><textarea id="htmlSource" class="code-input" aria-label="가져올 HTML" placeholder="&lt;div style=…&gt;\n  HTML 코드를 여기에 붙여넣으세요.\n&lt;/div&gt;">${e(maker?.original||'')}</textarea><div class="import-bottom"><span class="muted" style="font-size:12px">자동으로 찾지 못한 부분도 원본에 남겨둡니다.</span><span class="spacer"></span>${button('예시 HTML로 시작','sample-html','','soft')}${button('분석하고 부분 지정 →','analyze','','primary')}</div></div></div>`;
    const fieldSelected=maker.fields.find(f=>f.id===selectedNode?.id),confirmed=maker.fields.filter(f=>f.confirmed);return `<div class="maker-heading"><div><div class="eyebrow">HTML → YOUR PRESET</div><h1>바꿔 쓸 부분을 골라주세요</h1></div><div class="steps"><span class="step">1 가져오기 ✓</span><span class="step active">2 후보 확인 · 부분 지정</span><span class="step">3 이름 붙여 등록</span></div></div><div class="maker-layout"><aside class="maker-left"><div class="panel-card"><div class="row between"><h3>원본 HTML</h3><small>${maker.original.length.toLocaleString()}자</small></div><textarea id="makerSource" class="code-input" aria-label="원본 HTML">${e(maker.original)}</textarea><div class="row" style="margin-top:10px">${button('다시 분석','reanalyze','','small soft')}${button('파일 열기','html-file','','small')}</div></div><div class="panel-card"><h3>자동으로 찾은 것</h3>${[['title','제목'],['body','긴 본문'],['image','이미지'],['link','링크'],['repeat','반복 구역'],['text','짧은 글']].map(([r,t])=>`<div class="detect-row"><span>${t}</span><span class="badge">${maker.fields.filter(f=>f.role===r).length}</span></div>`).join('')}<p class="field-hint" style="margin-top:14px">후보를 누르고 역할을 확인해 주세요.<br>다른 부분은 미리보기에서 직접 고를 수 있어요.</p></div></aside>${previewPanel('maker-preview')}<aside class="maker-right"><div class="unassigned"><b>미확인 후보 ${maker.fields.filter(f=>!f.confirmed).length}개</b><br>지정하지 않은 부분은 원래 HTML에 남아요.</div>${selectedNode?`<div class="panel-card selection-card"><div class="row between"><h3>선택한 부분</h3><small>${e(selectedNode.tag||'')}</small></div><p class="field-hint" style="margin-bottom:13px;max-height:65px;overflow:auto">${e(selectedNode.text||fieldSelected?.default||'')}</p><label class="field"><span>역할</span><select id="fieldRole">${Object.entries(P.fieldNames).map(([r,t])=>`<option value="${r}" ${fieldSelected?.role===r?'selected':''}>${t}</option>`).join('')}</select></label><label class="field"><span>입력칸 이름</span><input id="fieldName" value="${e(fieldSelected?.name||'새 입력칸')}"></label><label class="field"><span>기본값</span><textarea id="fieldDefault" rows="2">${e(fieldSelected?.default||selectedNode.text||'')}</textarea></label>${button('이 역할로 지정','assign-field','','primary')}</div>`:''}<div class="panel-card"><div class="row between" style="margin-bottom:12px"><h3 style="margin:0">입력칸 후보 <span class="badge">${maker.fields.length}</span></h3>${button('모두 확인','confirm-fields','','text-button small')}</div><div class="field-list">${maker.fields.map(f=>`<button class="field-item ${selectedNode?.id===f.id?'active':''}" data-action="select-field" data-id="${e(f.id)}"><b>${f.confirmed?'✓ ':''}${e(f.name)}</b><span>${e(f.role)} · ${e(f.default||'비어 있음')}</span></button>`).join('')}</div></div>${button(`프리셋 등록 → (${confirmed.length}개 지정)`,'register-preset','','primary maker-register')}</aside></div>`;}
  function updatePreview(){const frame=$('previewFrame');if(!frame)return;if(route==='maker'){frame.srcdoc=P.documentHTML(maker.html,{interactive:true,mapping:true,fields:maker.fields});}else if(current())frame.srcdoc=P.documentHTML(P.render(current()),{interactive:true});}
  function selectNode(node){selectedNode=node;render();}
  function showSwitch(){const l=current();modal('내용은 그대로, 틀만 바꾸기',`<p class="muted" style="margin-bottom:17px">새 틀에서 쓰지 않는 전용 설정도 보관합니다.</p><div class="choice-grid">${state.presets.map(p=>`<button class="choice ${l.preset.id===p.id?'active':''}" data-action="apply-preset" data-id="${e(p.id)}"><b>${e(p.name)}</b><small>${e(p.description)}</small></button>`).join('')}</div>`);}
  function applyPreset(id){const l=current(),p=state.presets.find(x=>x.id===id);if(!p)return;if(id===l.preset.id&&l.preset.version===p.version){closeModal();return;}const upgrading=id===l.preset.id&&l.preset.version!==p.version;if(upgrading){const backup=P.clone(l);backup.id=P.uid();backup.title+=' · 이전 프리셋 백업';state.logs.unshift(backup);}const old={presetId:l.preset.id,name:l.preset.name,values:P.clone(l.values),custom:P.clone(l.custom),style:P.clone(l.style),styleOverrides:P.clone(l.styleOverrides||{}),designImages:P.clone(l.designImages||{})};l.orphaned=l.orphaned||[];const previous=upgrading?old:l.orphaned.find(x=>x.presetId===id);l.orphaned=l.orphaned.filter(x=>x.presetId!==id&&x.presetId!==old.presetId);l.orphaned.push(old);const fresh=P.createLog(p);imageSlot='main';mediaScene='';l.primarySceneId||=l.scenes[0].id;l.designImages={...(fresh.designImages||{}),...(previous?.designImages||{})};l.preset=fresh.preset;l.values={...fresh.values,...(previous?.values||{})};l.custom={...fresh.custom,...(previous?.custom||{})};l.style=previous?.style||fresh.style;l.styleOverrides=previous?.styleOverrides||{};closeModal();dirty();render();toast(upgrading?'새 형식을 적용하고 이전 로그는 백업 사본으로 보관했어요.':'내용을 보존하고 프리셋을 교체했어요.');}
  function showPresetOrder(focusId='',direction=''){
    const scrollTop=$('presetOrderList')?.scrollTop||0;
    modal('프리셋 순서 변경',`<p class="field-hint">왼쪽 ≡를 잡고 원하는 위치로 끌어 옮기세요. 자동 저장돼요.</p><ol id="presetOrderList" class="preset-order-list">${state.presets.map((p,i)=>`<li data-preset-id="${e(p.id)}">${button('≡','',`data-id="${e(p.id)}" aria-label="${e(p.name)} 끌어서 이동" title="잡고 끌어서 이동"`,'preset-drag-handle')}<span class="preset-order-number">${i+1}</span><span class="preset-order-name">${e(p.name)}</span>${button('↑','move-preset',`data-id="${e(p.id)}" data-value="-1" aria-label="${e(p.name)} 위로" ${i===0?'disabled':''}`)}${button('↓','move-preset',`data-id="${e(p.id)}" data-value="1" aria-label="${e(p.name)} 아래로" ${i===state.presets.length-1?'disabled':''}`)}</li>`).join('')}</ol><div class="dialog-actions">${button('완료','close-dialog','','primary')}</div>`);
    $('presetOrderList').scrollTop=scrollTop;
    if(focusId){const controls=[...$('presetOrderList').querySelectorAll('button')].filter(b=>b.dataset.id===focusId&&!b.disabled);const target=controls.find(b=>b.dataset.value===direction)||controls[0];target?.focus({preventScroll:true});target?.closest('li').scrollIntoView({block:'nearest'});}
  }
  function movePreset(id,direction){
    const from=state.presets.findIndex(p=>p.id===id),to=from+Number(direction);
    if(from<0||![-1,1].includes(Number(direction))||to<0||to>=state.presets.length)return;
    state.presets.splice(to,0,state.presets.splice(from,1)[0]);state.presetOrderCustomized=true;
    dirty(false);render();showPresetOrder(id,direction);
    toast(`${state.presets[to].name}: ${to+1}번째로 이동했어요.`);
  }
  let presetDrag=null;
  function updatePresetDrag(){
    const d=presetDrag;if(!d)return;
    const bounds=d.list.getBoundingClientRect();
    const rows=[...d.list.children].filter(row=>row!==d.row);
    const before=rows.find(row=>{const box=row.getBoundingClientRect();return d.y<box.top+box.height/2;});
    if(before!==d.row.nextElementSibling)d.list.insertBefore(d.row,before||null);
    [...d.list.children].forEach((row,i)=>row.querySelector('.preset-order-number').textContent=i+1);
    const speed=d.y<bounds.top+48?-Math.min(14,(bounds.top+48-d.y)/3):d.y>bounds.bottom-48?Math.min(14,(d.y-bounds.bottom+48)/3):0;
    d.list.scrollTop+=speed;
    d.frame=requestAnimationFrame(updatePresetDrag);
  }
  function finishPresetDrag(commit,refresh=true){
    const d=presetDrag;if(!d)return;
    presetDrag=null;cancelAnimationFrame(d.frame);
    if(d.list.hasPointerCapture(d.pointerId))d.list.releasePointerCapture(d.pointerId);
    d.row.classList.remove('dragging');d.list.classList.remove('is-dragging');
    if(commit&&d.started){
      const ids=[...d.list.children].map(row=>row.dataset.presetId);
      const to=ids.indexOf(d.id),from=state.presets.findIndex(p=>p.id===d.id);
      if(to!==from){
        const byId=new Map(state.presets.map(p=>[p.id,p]));state.presets=ids.map(id=>byId.get(id));state.presetOrderCustomized=true;
        dirty(false);render();toast(`${state.presets[to].name}: ${to+1}번째로 이동했어요.`);
      }
    }
    if(refresh&&dialog.open)showPresetOrder(d.id);
  }
  document.addEventListener('pointerdown',event=>{
    const handle=event.target.closest('.preset-drag-handle');
    if(!handle||event.button!==0||!event.isPrimary||presetDrag)return;
    const list=$('presetOrderList'),row=handle.closest('li');
    event.preventDefault();handle.focus({preventScroll:true});
    presetDrag={id:row.dataset.presetId,row,list,pointerId:event.pointerId,startY:event.clientY,y:event.clientY,started:false,frame:0};
    list.setPointerCapture(event.pointerId);
  });
  document.addEventListener('pointermove',event=>{
    const d=presetDrag;if(!d||event.pointerId!==d.pointerId)return;
    d.y=event.clientY;
    if(!d.started&&Math.abs(d.y-d.startY)>4){d.started=true;d.row.classList.add('dragging');d.list.classList.add('is-dragging');updatePresetDrag();}
  });
  document.addEventListener('pointerup',event=>{if(presetDrag?.pointerId===event.pointerId)finishPresetDrag(true);});
  document.addEventListener('pointercancel',event=>{if(presetDrag?.pointerId===event.pointerId)finishPresetDrag(false);});
  document.addEventListener('lostpointercapture',event=>{if(presetDrag?.pointerId===event.pointerId)finishPresetDrag(false);});
  dialog.addEventListener('cancel',()=>finishPresetDrag(false,false));
  dialog.addEventListener('close',()=>finishPresetDrag(false,false));
  function showPresetMenu(id){const p=state.presets.find(x=>x.id===id);modal(p.name,`<label class="field"><span>프리셋 이름</span><input id="renamePreset" value="${e(p.name)}" maxlength="80"></label><div class="row wrap">${button('이름 저장','rename-preset',`data-id="${e(id)}"`,'primary')}${button('파일로 내보내기','export-preset',`data-id="${e(id)}"`)}${p.kind==='custom'?button('입력칸 편집','edit-preset',`data-id="${e(id)}"`):''}</div><p class="field-hint" style="margin-top:17px">이 프리셋으로 이미 만든 로그는 바뀌지 않아요.</p>`);}
  async function exportHTML(){const l=current();const body=P.render(l),doc=new DOMParser().parseFromString(body,'text/html');doc.querySelectorAll('*').forEach(n=>[...n.attributes].filter(a=>a.name.startsWith('data-pm-')||['data-scene','data-line','data-field'].includes(a.name)).forEach(a=>n.removeAttribute(a.name)));const html=doc.head.innerHTML+doc.body.innerHTML;modal('게시용 HTML',`<p class="muted" style="margin-bottom:13px">아래 코드를 게시판의 HTML 편집 화면에 붙여넣으세요.</p>${/data:image/.test(html)?'<div class="note sand" style="margin-bottom:12px">파일 이미지를 포함하고 있어요. 게시판이 파일 이미지 주소를 요구하면 먼저 이미지 탭에서 게시용 주소로 교체해 주세요.</div>':''}<textarea id="exportCode" class="output-code" aria-label="게시용 HTML" readonly>${e(html)}</textarea><div class="dialog-actions">${button('HTML 복사 → 아카 편집기','open-editor')}${button('HTML 복사 → 이미지 변환','open-image-tool')}${button('HTML 파일 저장','download-html')}${button('HTML 복사','copy-html','','primary')}</div>`);}
  function validatePreset(p){if(!p||typeof p.name!=='string'||p.name.length>100||!['custom','letter',...P.seeds().map(x=>x.kind)].includes(p.kind))throw new Error('올바른 프리셋 파일이 아니에요.');if(p.kind==='custom'){if(typeof p.html!=='string'||!Array.isArray(p.fields)||p.fields.length>500)throw new Error('입력칸 정보를 읽을 수 없어요.');p.html=P.sanitize(p.html).html;p.fields=p.fields.filter(f=>/^n\d+$/.test(f.id)&&P.fieldRoles.includes(f.role));p.special=[];}else{const base=P.seeds().find(x=>x.kind===p.kind);if(base&&!p.design)p.special=base.special;if(p.design){if(!p.design.html||!Array.isArray(p.design.fields)||!Array.isArray(p.design.images)||!p.design.templates)throw new Error('디자인 정보를 읽을 수 없어요.');p.design.html=P.sanitize(p.design.html).html;for(const key of Object.keys(p.design.templates))p.design.templates[key]=P.sanitize(p.design.templates[key]).html;p.special=p.design.fields;}}return p;}
  async function importFile(file){const data=JSON.parse(await file.text());if(data.format!=='log-studio-preset-maker'||data.version!==1)throw new Error('이 도구에서 저장한 프리셋·프로젝트·백업 파일을 선택해 주세요.');let presets=[],logs=[];if(data.type==='preset')presets=[data.data];else if(data.type==='presets')presets=data.data;else if(data.type==='project')logs=[data.data];else if(data.type==='backup'){presets=data.data.presets;logs=data.data.logs;}else throw new Error('지원하지 않는 파일 형식이에요.');if(!Array.isArray(presets)||!Array.isArray(logs))throw new Error('파일의 자료 구성을 확인해 주세요.');const safePresets=presets.map(raw=>{const p=validatePreset(P.clone(raw));p.id=P.uid();return p;});const safeLogs=logs.map(raw=>{const l=P.clone(raw);validatePreset(l.preset);if(!Array.isArray(l.scenes)||!l.scenes.length||!l.scenes.every(s=>typeof s.body==='string')||typeof l.title!=='string'||!l.style||!l.image)throw new Error('로그 자료가 불완전해요.');l.id=P.uid();l.scenes.forEach(s=>{const oldId=s.id;s.id=P.uid();if(l.primarySceneId===oldId)l.primarySceneId=s.id;});if(l.preset.design?.editor&&!l.scenes.some(s=>s.id===l.primarySceneId))l.primarySceneId=l.scenes[0].id;l.values=l.values||{};l.custom=l.custom||{};l.updatedAt=Date.now();return l;});state.presets.push(...safePresets);state.logs.unshift(...safeLogs);dirty();render();toast(`${safePresets.length}개 프리셋 · ${safeLogs.length}개 로그를 사본으로 가져왔어요.`);}
  function analyzeSource(source){if(!source.trim()||!/<[a-z][\s\S]*>/i.test(source))return toast('HTML 코드를 넣어 주세요.');maker=P.analyze(source);selectedNode=null;dirty();setRoute('maker');}
  async function loadImage(file){if(!/^image\/(png|jpeg|gif|webp)$/.test(file.type))return toast('PNG·JPEG·GIF·WebP 이미지를 선택해 주세요.');if(file.size>10*1024*1024)return toast('이미지는 10MB 이하로 넣어 주세요.');const reader=new FileReader();reader.onload=()=>{activeImage(current()).src=reader.result;dirty();render();};reader.onerror=()=>toast('이미지를 읽지 못했어요.');reader.readAsDataURL(file);}
  function help(syntax=false){modal(syntax?'익숙한 문법으로, 한 번에':'프리셋 제조기 사용법',`<div class="help-content">${syntax?'':`<p><b>1. 보관함</b><br>프리셋을 고르고 ‘로그 쓰기’를 누르세요. 작성한 로그는 별도로 저장돼요.</p><p><b>2. 내 HTML로 만들기</b><br>HTML을 가져와 미리보기의 제목·본문 등을 클릭하고 입력칸 역할을 지정하세요.</p><p><b>3. 로그 작성</b><br>원고를 통째로 붙여넣고 이미지·모양·프리셋 전용 설정을 조절하세요.</p>`}<pre>서술을 그대로 붙여넣으세요.\n\n&lt;&lt;세린&gt;&gt; "문이 열렸어."\n**카엘** "안으로 들어가자."\n\n*강조* · **굵게** · '속마음'\n&gt;&gt;"캐릭터 대사"\n&lt;&lt;"유저 대사"\n[C] 가운데 · [|] 가운데 · [&gt;] 오른쪽\n# 큰 제목 · #### 작은 제목\n&gt; 인용문\n[HR] · [HR2] · [HR3] · [GAP]\n[IMG https://example.com/photo.jpg @60 | 캡션]\n[IMG:https://example.com/photo.jpg:60]\n[FN:단어]주석[/FN]\n[접기 회상]\n접어서 보관할 내용\n[/접기]</pre><p class="muted">조각로그·로그 다이어리 개조판의 공통 입력 문법을 지원해요. 문법 표시는 각각 한 줄에 입력하세요. 지원하지 않는 문법은 원문으로 남아요.</p><p>화자가 없는 대사는 이름을 추측하지 않아요. 프리셋을 바꿔도 원고와 연결되지 않은 설정은 보존해요.</p><p class="muted">자동 저장은 이 브라우저 안에 저장돼요. 전체 백업이나 프로젝트 파일로도 보관해 주세요.</p></div>`);}
  document.addEventListener('click',async event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id,val=b.dataset.value,l=current();try{switch(a){
    case 'route':setRoute(val);break;
    case 'library-tab':libraryTab=val;query='';render();break;
    case 'filter':filter=val;render();break;
    case 'preset-order':showPresetOrder();break;
    case 'move-preset':movePreset(id,val);break;
    case 'favorite':{const p=state.presets.find(x=>x.id===id);p.favorite=!p.favorite;dirty();render();break;}
    case 'new-log':{const p=state.presets.find(x=>x.id===id)||l?.preset||state.presets[0];if(p)newLog(p);break;}
    case 'open-log':mediaScene='';imageSlot='main';currentId=id;setRoute('editor');break;
    case 'duplicate-preset':{const p=P.clone(state.presets.find(x=>x.id===id));p.id=P.uid();p.name+=' 사본';state.presets.push(p);dirty();render();toast('프리셋을 복제했어요.');break;}
    case 'preset-menu':showPresetMenu(id);break;
    case 'rename-preset':{const name=$('renamePreset').value.trim();if(!name)return;state.presets.find(x=>x.id===id).name=name;dirty();closeModal();render();break;}
    case 'export-preset':download(state.presets.find(x=>x.id===id).name+'.lspreset',packageOf('preset',state.presets.find(x=>x.id===id)));break;
    case 'edit-preset':{const p=state.presets.find(x=>x.id===id);maker={original:p.original,html:p.html,fields:P.clone(p.fields),editingId:p.id};selectedNode=null;closeModal();setRoute('maker');break;}
    case 'export-library':if(libraryTab==='presets')download('프리셋-보관함.json',packageOf('presets',state.presets));else download('프리셋제조기-전체백업.json',packageOf('backup',state));break;
    case 'backup':download('프리셋제조기-전체백업-'+new Date().toISOString().slice(0,10)+'.json',packageOf('backup',state));toast('전체 백업을 내려받았어요.');break;
    case 'import':pickFile('.json,.lspreset,.lsproject',importFile);break;
    case 'export-project':download((l.title||'로그')+'.lsproject',packageOf('project',l));break;
    case 'log-menu':modal('로그 관리',`<div class="row">${button('로그 복제','duplicate-log',`data-id="${e(id)}"`)}${button('프로젝트 저장','export-log',`data-id="${e(id)}"`,'primary')}</div>`);break;
    case 'duplicate-log':{const copy=P.clone(state.logs.find(x=>x.id===id));if(l.preset.design?.editor){copy.designStates||={};copy.designStates[l.preset.id]=P.clone(window.PMEditors.sceneData(l,l.scenes[i]));}copy.id=P.uid();copy.title+=' 사본';copy.updatedAt=Date.now();state.logs.unshift(copy);dirty();closeModal();render();break;}
    case 'export-log':{const log=state.logs.find(x=>x.id===id);download(log.title+'.lsproject',packageOf('project',log));break;}
    case 'editor-tab':editorTab=val;render();break;
    case 'device':device=val;$('previewFrame')?.classList.toggle('mobile',device==='mobile');document.querySelectorAll('[data-action="device"]').forEach(x=>x.classList.toggle('active',x.dataset.value===device));break;
    case 'mobile-view':mobilePreview=val==='preview';render();break;
    case 'switch-preset':showSwitch();break;
    case 'apply-preset':applyPreset(id);break;
    case 'add-scene':l.scenes.push({id:P.uid(),title:(l.preset.design?.editor?.unit||'장면')+' '+(l.scenes.length+1),subtitle:'',body:'',hidden:false});dirty();render();break;
    case 'duplicate-scene':{const i=l.scenes.findIndex(s=>s.id===id),copy=P.clone(l.scenes[i]);copy.id=P.uid();copy.title+=' 사본';l.scenes.splice(i+1,0,copy);dirty();render();break;}
    case 'hide-scene':{const s=l.scenes.find(s=>s.id===id);s.hidden=!s.hidden;dirty();render();break;}
    case 'move-scene':{const i=l.scenes.findIndex(s=>s.id===id),j=i+Number(val);if(j>=0&&j<l.scenes.length){[l.scenes[i],l.scenes[j]]=[l.scenes[j],l.scenes[i]];dirty();render();}break;}
    case 'format':{const t=$('bodyInput'),start=t.selectionStart,end=t.selectionEnd,selected=t.value.slice(start,end)||'내용';const formats={bold:`**${selected}**`,em:`*${selected}*`,hr:'\n[HR]\n',fold:`\n[접기 제목]\n${selected}\n[/접기]\n`,speaker:`<<화자>> "${selected}"`};t.setRangeText(formats[b.dataset.format],start,end,'select');l.scenes[0].body=t.value;dirty();updatePreview();t.focus();break;}
    case 'find':findOpen=!findOpen;render();break;
    case 'replace-all':{const find=$('findText').value,replacement=$('replaceText').value,hidden=$('includeHidden').checked;if(!find)return;let n=0;l.history=(l.history||[]).slice(-4);l.history.push({at:Date.now(),scenes:P.clone(l.scenes)});for(const s of l.scenes){if(s.hidden&&!hidden)continue;n+=s.body.split(find).length-1;s.body=s.body.split(find).join(replacement);}dirty();render();toast(`${n}곳을 바꿨어요. 이전 원고는 프로젝트 기록에 보관했어요.`);break;}
    case 'list-add':{const key=b.dataset.key,f=l.preset.special.find(f=>f.key===key);mediaData(l).values[key].push(f.type==='list'?'새 항목':{text:'새 목표',done:false});dirty();render();break;}
    case 'list-remove':{const values=mediaData(l).values,i=Number(b.dataset.index);values[b.dataset.key].splice(i,1);if(b.dataset.key==='choiceList'){if(values.choiceSelected===i+1)values.choiceSelected=0;else if(values.choiceSelected>i+1)values.choiceSelected--;}dirty();render();break;}
    case 'list-move':{const arr=mediaData(l).values[b.dataset.key],i=Number(b.dataset.index);if(i>0){[arr[i],arr[i-1]]=[arr[i-1],arr[i]];if(b.dataset.key==='choiceList'){const values=mediaData(l).values;if(values.choiceSelected===i+1)values.choiceSelected=i;else if(values.choiceSelected===i)values.choiceSelected=i+1;}}dirty();render();break;}
    case 'card-back-png':case 'card-png':{if(b.disabled)break;b.disabled=true;const oldText=b.textContent;b.textContent='한 장으로 저장 중…';try{const blob=await window.PMPhoto.cardPNG(P.clone(l),b.dataset.action==='card-back-png'?'back':imageSlot,l.preset.design?.editor?(mediaScene||l.primarySceneId||l.scenes[0].id):'');download((l.title||'체키')+'-프레임포함.png',blob,'image/png');toast('사진과 프레임 안의 글씨·장식을 함께 저장했어요.');}finally{b.disabled=false;b.textContent=oldText;}break;}
    case 'photo-only':{const blob=await window.PMPhoto.png(activeImage(l));download((l.title||'사진')+'-사진만.png',blob,'image/png');toast('현재 비율과 위치로 사진만 저장했어요.');break;}
    case 'film-add':{const photos=window.PMEditors.collection(l,mediaData(l)),photo={id:P.uid(),caption:'새 사진',hidden:false,image:{src:'',ratio:'3/2',width:100,x:50,y:50}};photos.push(photo);imageSlot='film:'+photo.id;dirty();render();break;}
    case 'film-select':imageSlot='film:'+id;render();break;
    case 'film-copy':case 'film-up':case 'film-down':case 'film-hide':{const photos=window.PMEditors.collection(l,mediaData(l)),i=photos.findIndex(p=>p.id===id);if(i<0)break;const action=b.dataset.action;if(action==='film-copy'){const copy=P.clone(photos[i]);copy.id=P.uid();photos.splice(i+1,0,copy);imageSlot='film:'+copy.id;}else if(action==='film-hide')photos[i].hidden=!photos[i].hidden;else{const to=i+(action==='film-up'?-1:1);if(to>=0&&to<photos.length)[photos[i],photos[to]]=[photos[to],photos[i]];}dirty();render();break;}
    case 'image-file':pickFile('image/png,image/jpeg,image/webp,image/gif',loadImage);break;
    case 'image-clear':activeImage(l).src='';dirty();render();break;
    case 'accent':l.style.accent=val;l.styleOverrides={...l.styleOverrides,accent:true};dirty();render();break;
    case 'scene-style':l.scenes.find(s=>s.id===$('styleScene').value).style={size:Number($('sceneSize').value),ink:$('sceneInk').value};dirty();updatePreview();toast('선택 장면에 적용했어요.');break;
    case 'save-styled-preset':{const p=P.clone(l.preset);p.id=P.uid();p.name+=' · 내 모양';p.font=l.style.font;p.paper=l.style.paper;p.ink=l.style.ink;p.accent=l.style.accent;p.savedStyle=P.clone(l.style);p.savedStyleOverrides=P.clone(l.styleOverrides||{});state.presets.push(p);dirty();toast('새 프리셋으로 보관함에 저장했어요.');break;}
    case 'export-html':await exportHTML();break;
    case 'open-editor':case 'open-image-tool':{try{await navigator.clipboard.writeText($('exportCode').value);window.open(a==='open-editor'?'../arca-builder/':'../html-to-image/','_blank','noopener');toast('HTML을 복사했어요. 열린 도구의 HTML 입력칸에 붙여넣으세요.');}catch{toast('복사하지 못했어요. HTML 파일로 저장해서 기존 편집기에서 열어 주세요.');}break;}
    case 'download-html':download((l.title||'로그')+'.html',P.documentHTML($('exportCode').value),'text/html');break;
    case 'copy-html':try{await navigator.clipboard.writeText($('exportCode').value);toast('게시용 HTML을 복사했어요.');}catch{$('exportCode').select();toast('Ctrl+C로 선택된 HTML을 복사해 주세요.');}break;
    case 'sample-html':analyzeSource(P.sampleHTML);break;
    case 'analyze':analyzeSource($('htmlSource').value);break;
    case 'reanalyze':analyzeSource($('makerSource').value);break;
    case 'html-file':pickFile('.html,.htm,.txt',async file=>analyzeSource(await file.text()));break;
    case 'select-field':{const f=maker.fields.find(f=>f.id===id);selectNode({id,text:f.default});break;}
    case 'assign-field':{const role=$('fieldRole').value,name=$('fieldName').value.trim()||'입력칸',value=$('fieldDefault').value;let f=maker.fields.find(f=>f.id===selectedNode.id);if(!f){f={id:selectedNode.id};maker.fields.push(f);}Object.assign(f,P.describeField(maker.html,f.id,role)||{},{role,name,default:value,confirmed:true});if(['title','subtitle','body'].includes(role))maker.fields.forEach(other=>{if(other!==f&&other.role===role){other.role='text';other.confirmed=false;}});dirty();render();break;}
    case 'confirm-fields':maker.fields.forEach(f=>f.confirmed=true);dirty();render();break;
    case 'register-preset':if(!maker.fields.some(f=>f.confirmed&&f.role!=='fixed')){toast('입력칸을 하나 이상 확인해 주세요.');break;}modal('새 프리셋 이름',`<label class="field"><span>이름</span><input id="newPresetName" value="${e(maker.suggestedName||'나의 HTML 프리셋')}" maxlength="80"></label><p class="muted">확인한 입력칸만 연결해요. 나머지는 원본 모양으로 남아요.</p><div class="dialog-actions">${button('보관함에 저장','finish-preset','','primary')}</div>`);break;
    case 'finish-preset':{const name=$('newPresetName').value.trim();if(!name)return;const p={id:P.uid(),kind:'custom',name,description:'직접 만든 HTML · '+maker.fields.filter(f=>f.confirmed).length+'개 입력칸',category:'내 프리셋',font:"'Gowun Batang',serif",paper:'#ffffff',ink:'#38333c',accent:'#8888CC',original:maker.original,html:maker.html,fields:P.clone(maker.fields.filter(f=>f.confirmed)),special:[],favorite:false,version:1,createdAt:Date.now()};state.presets.push(p);maker=null;selectedNode=null;dirty();closeModal();filter='all';libraryTab='presets';setRoute('library');toast('프리셋을 보관함에 등록했어요.');break;}
    case 'syntax':help(true);break;
    case 'help':help();break;
    case 'close-dialog':closeModal();break;
  }}catch(err){console.error(err);toast('처리하지 못했어요: '+err.message);}});
  document.addEventListener('input',event=>{const t=event.target,l=current();if(t.id==='mediaScene'){mediaScene=t.value;imageSlot='main';render();return;}if(t.id==='imageSlot'){imageSlot=t.value;render();return;}if(t.id==='librarySearch'){query=t.value;const pos=t.selectionStart;render();$('librarySearch').focus();$('librarySearch').setSelectionRange(pos,pos);return;}if(t.id==='htmlSource'){maker={original:t.value};state.maker=maker;dirty();return;}if(route!=='editor'||!l)return;
    if(t.dataset.filmCaption){const p=window.PMEditors.collection(l,mediaData(l)).find(p=>p.id===t.dataset.filmCaption);if(p)p.caption=t.value;}
    else if(t.dataset.sceneBody){l.scenes.find(s=>s.id===t.dataset.sceneBody).body=t.value;const count=$('charCount');if(count)count.textContent=l.scenes.reduce((n,s)=>n+s.body.length,0).toLocaleString()+'자 · '+l.scenes.length+'개 장면';}
    else if(t.dataset.sceneTitle){const scene=l.scenes.find(s=>s.id===t.dataset.sceneTitle);scene.title=t.value;if(l.preset.design?.editor&&scene.id===l.primarySceneId){l.title=t.value;$('editorHeading').textContent=t.value;}}
    else if(t.dataset.listText){const f=l.preset.special.find(f=>f.key===t.dataset.listText),i=Number(t.dataset.index);if(f.type==='checklist')mediaData(l).values[f.key][i].text=t.value;else mediaData(l).values[f.key][i]=t.value;}
    else if(t.dataset.listCheck){mediaData(l).values[t.dataset.listCheck][Number(t.dataset.index)].done=t.checked;}
    else if(t.dataset.bind){const path=t.dataset.bind.split('.');const activePhoto=path[0]==='activePhoto';if(activePhoto)path.shift();if(path.some(k=>['__proto__','constructor','prototype'].includes(k)))return;let target=activePhoto?activeImage(l):/^(image|designImages|values)\./.test(t.dataset.bind)?mediaData(l):l;for(const k of path.slice(0,-1))target=target[k];let value=t.type==='checkbox'?t.checked:['number','range'].includes(t.type)?Number(t.value):t.value;if(t.type==='number'&&t.value==='')return;if(t.type==='number'){if(t.min!=='')value=Math.max(Number(t.min),value);if(t.max!=='')value=Math.min(Number(t.max),value);}target[path.at(-1)]=value;if(t.dataset.bind==='title'){$('editorHeading').textContent=value||'제목 없는 로그';if(l.preset.design?.editor)(l.scenes.find(s=>s.id===l.primarySceneId)||l.scenes[0]).title=value;}if(t.dataset.bind==='subtitle'&&l.preset.design?.editor)(l.scenes.find(s=>s.id===l.primarySceneId)||l.scenes[0]).subtitle=value;if(/^scenes\.\d+\.subtitle$/.test(t.dataset.bind)&&l.scenes[Number(path[1])]?.id===l.primarySceneId)l.subtitle=value;document.querySelectorAll('[data-range-value]').forEach(o=>{if(o.dataset.rangeValue===t.dataset.bind)o.textContent=value+'%';});}
    else return;if(t.dataset.bind?.startsWith('style.')){l.styleOverrides=l.styleOverrides||{};l.styleOverrides[t.dataset.bind.split('.')[1]]=true;}dirty();updatePreview();
  });
  window.addEventListener('message',event=>{const frame=$('previewFrame');if(!frame||event.source!==frame.contentWindow||!event.data)return;const d=event.data;if(d.type==='pm-height'&&Number.isFinite(d.height)){frame.style.height=Math.min(60000,Math.max(650,d.height))+'px';return;}if(d.type!=='pm-pick')return;if(route==='maker'&&/^n\d+$/.test(d.node)){selectNode({id:d.node,text:String(d.text||''),tag:d.tag});return;}if(route==='editor'){if(current().preset.design?.editor&&d.scene)mediaScene=d.scene;if(d.focus==='image'){imageSlot=current().preset.design&&d.field?d.field:'main';editorTab='images';mobilePreview=false;render();return;}editorTab='content';mobilePreview=false;render();let target;if(d.focus==='body'){const scene=current().scenes.find(s=>s.id===d.scene)||current().scenes[0];target=document.querySelector(`[data-scene-body="${scene.id}"]`);if(target){target.closest('details')?.setAttribute('open','');const line=Number(d.line)||0,start=scene.body.split('\n').slice(0,line).join('\n').length+(line?1:0);target.focus();target.setSelectionRange(start,start+(scene.body.split('\n')[line]?.length||0));}}else if(d.focus==='scene-title'){target=document.querySelector(`[data-scene-title="${d.scene||current().scenes[0].id}"]`);target?.closest('details')?.setAttribute('open','');}else target=document.querySelector(`[data-bind="${['title','subtitle','note'].includes(d.focus)?d.focus:d.focus==='value'?'values.'+d.field:'custom.'+d.field}"]`);target?.closest('details')?.setAttribute('open','');target?.focus();target?.scrollIntoView({behavior:'smooth',block:'center'});}});
  document.addEventListener('paste',event=>{if(route!=='editor'||editorTab!=='images')return;const image=[...(event.clipboardData?.files||[])].find(f=>f.type.startsWith('image/'));if(image){event.preventDefault();loadImage(image);}});
  document.addEventListener('dragover',event=>{if(event.target.closest('#imageDrop'))event.preventDefault();});
  document.addEventListener('drop',event=>{if(event.target.closest('#imageDrop')){event.preventDefault();const file=event.dataTransfer.files[0];if(file)loadImage(file);}});
  document.addEventListener('keydown',event=>{if(event.target.id==='imageDrop'&&['Enter',' '].includes(event.key)){event.preventDefault();pickFile('image/*',loadImage);}if((event.ctrlKey||event.metaKey)&&event.key==='s'){event.preventDefault();flush().then(ok=>{if(ok)toast('현재 작업을 저장했어요.');});}});
  window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(['library','maker','editor'].includes(next)&&next!==route)setRoute(next);});
  window.addEventListener('resize',()=>{if(route==='library')document.querySelectorAll('[data-thumb]').forEach(f=>f.style.transform=`scale(${f.parentElement.clientWidth/640})`);});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&state)flush();});
  window.addEventListener('pagehide',()=>{if(state)flush();});
  window.addEventListener('beforeunload',event=>{if(pendingSave){try{if(localStorage.getItem('preset-maker-recovery'))return;}catch{}event.preventDefault();event.returnValue='';}});
  async function init(){try{state=await P.readStore();const recovery=JSON.parse(localStorage.getItem('preset-maker-recovery')||'null');if(recovery&&(!state||recovery.savedAt>=(state.savedAt||0)))state=recovery;}catch(err){status('저장 공간에 연결하지 못했어요');console.error(err);}if(!state)state={presets:P.seeds(),logs:[],lastLogId:'',maker:null};const newPresets=P.seeds();if(state.presets.some(p=>p.id.startsWith('builtin-')&&(p.version||1)<3)){try{if(!localStorage.getItem('preset-maker-before-original-design'))localStorage.setItem('preset-maker-before-original-design',JSON.stringify(state));}catch{}}
    for(const preset of newPresets){const at=state.presets.findIndex(p=>p.id===preset.id);if(at<0)state.presets.push(preset);else if((state.presets[at].version||1)<preset.version){const old=state.presets[at];state.presets[at]={...preset,name:old.name,favorite:old.favorite,savedStyle:old.savedStyle,savedStyleOverrides:old.savedStyleOverrides};}}
    if(state.lastLogId){const log=state.logs.find(l=>l.id===state.lastLogId);if(log?.preset.design&&!log.designImages)log.designImages=P.createLog(log.preset).designImages;}
    const originalIndex=state.presets.findIndex(p=>p.id==='builtin-original-html');if(originalIndex>0&&!state.presetOrderCustomized)state.presets.unshift(state.presets.splice(originalIndex,1)[0]);
    maker=state.maker||null;currentId=state.lastLogId||'';const next=location.hash.slice(1);setRoute(['maker','editor'].includes(next)?next:'library');}
  init();
})();
